-- drop dependencies
alter table if exists user_group drop constraint if exists fk_user_group_user;
-- apply changes
create table "user" (
  id                            bigint generated by default as identity not null,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  deleted                       boolean default false not null,
  first_name                    varchar(255),
  last_name                     varchar(255),
  email                         varchar(255),
  avatar                        varchar(255),
  google_auth_id                varchar(255),
  constraint uq_user_email unique (email),
  constraint uq_user_email unique (email),
  constraint pk_user primary key (id)
);

-- foreign keys and indices
alter table user_group add constraint fk_user_group_user foreign key (user_id) references "user" (id) on delete restrict on update restrict;
